# This is a basic workflow to help you get started with Actions

name: Build and Deploy to Staging area

on:
  push:
    branches: 
    - develop
  workflow_dispatch:
  
env:
  IMAGE: rtr-app
  NODE_VERSION: 12.18.3

jobs:
  build:
    name: deploy to staging
    runs-on: ubuntu-latest
    environment: staging
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION}}
        
      - name: Build
        run: |-
          docker build \
          --tag $IMAGE \
          rtr
        
